/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Testimonial = IDL.Record({
  'clientName' : IDL.Text,
  'feedback' : IDL.Text,
  'company' : IDL.Text,
  'profileImageUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'addTestimonial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getTestimonial' : IDL.Func([IDL.Text], [IDL.Opt(Testimonial)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Testimonial = IDL.Record({
    'clientName' : IDL.Text,
    'feedback' : IDL.Text,
    'company' : IDL.Text,
    'profileImageUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'addTestimonial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getTestimonial' : IDL.Func([IDL.Text], [IDL.Opt(Testimonial)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };